### ISSUE TITLE
Uptime checker querying parent domain instead of subdomain

### ISSUE THREAD

**Issue by ghost** [tiekoettercom/searx-instances-uptime#603]
Hi there,

The SearX and SearXNG instances uptime checker is querying the parent domain asynchronousexchange.com instead of the meta-search engine at search.asynchronousexchange.com . 

Notice that search.asynchronousexchange.com is an IPv6-only instance, and the queries come all from IPv4 addresses. If the server(s) where the uptime checker is hosted lacks an IPv6, you can freely add an IP 6-over-4 tunnel from https://tunnelbroker.net .

Regards.

**Comment by tiekoetter** [comment]
So you are 100% right but this uptime checker is powered 100% (except my domain) by GitHub, which as you probably know lacks IPv6 support. I intentionally set the 2nd level domain to be checked because I think it is a better solution than not checking it at all.

If you have any additional advice please let me know.

**Comment by ghost** [comment]
OK, is fine for me.
I'll mark this issue as closed.
